### ISSUE TITLE
Docs don't use available space and it makes tables hard to read.

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/docs#83]
Current behavior:
![image](https://user-images.githubusercontent.com/886059/183863527-9a1e925d-e173-4295-8307-e3cb6f8f1ef1.png)

Desired Behavior:
![image](https://user-images.githubusercontent.com/886059/183863858-e3734198-14a0-436d-8590-45e7b49126c6.png)

The above is just a couple of CSS changes that make the page fill available space.  You could improve it further by making the columns not all the same width, but that is a problem specific to this page and a much bigger change so for now I'm just lobbying for the very simple removal of hard-coded widths.

For reference, here is the getting started page with the same settings:
![image](https://user-images.githubusercontent.com/886059/183864195-07dbbcc8-656c-463f-9755-7c0038f995df.png)

Note that it is still quite pleasing to read, and I argue better than the current version.

I tried looking for CSS files in this repository but couldn't find them, so I'm not actually sure how/where to make this change.

**Comment by rubo** [comment]
Fixed in new docs

**Comment by MicahZoltu** [comment]
I'm still seeing a large amount of extraneous whitespace.  Is this fix not live yet?  If not, when will it go live and/or is there a place I can check out a preview of it?
![image](https://github.com/NethermindEth/docs/assets/886059/03e6456d-b0b3-4476-87d8-949976dcd7c4)

**Comment by rubo** [comment]
By "fixed," I mean we no longer have tables and horizontal spacing issues with them.

Now, about unused white spaces. Although expanding text to take all the available screen space is possible, it makes it harder to read. We haven't explicitly chosen that; it's the template's default behavior and makes sense from a readability perspective. While it might not look aesthetically pleasing on wide screens, it remains easily readable and centered.

**Comment by rubo** [comment]
While I admit that the default max width could be wider, taking the entire screen space on very wide screens doesn't help readability, quite the opposite. Generally, reading newspaper-sized texts is easier than reading very long horizontal ones. Of course, it depends on the content, but this is generally the case. When it comes to long code snippets, we'd prefer to make them multiline rather than expanding the pages.

With this said, we would consider changing the width once we have issues like the one with the tables you mentioned initially.
